dist: bionic

before_install:
- sudo apt-get update
- sudo apt-get -y install pandoc texlive texlive-xetex lmodern

script: make

after_success:
  - ./push.sh

env:
  global:
    secure: OJb/YTgAsD+OzF6oG0xhNlWrcwjTvurTWdBpydcEZFGHY4kH9Aipw/Lvx2goap+aWD6ZqITXzJNC7QUjkktINgh/8Yg39ru6fQviQGFqd5LS0BW/AHDzssv/6TA7u48r6xUklbL35Lr/KvmVF2mLXAvO9hYubO9f6m1nL+38hmQyej8iCxJADdRBWbegzNBOZU2W7nnfCdyF8fjcLOLLbcdSq4ZURq/5tdej+YoBYGf9efTLsjgfh/SNXEppT1dOXPc5XASKeLjSBuVYOxdjnyFopeG8BtojnAJs6/lL8TyC8aDe9F+cQmLeazghibEVQL5a6UjLsH6zXZoiW2N7dag2W7bmrm5rCfjGI+YbjqBZwcgHPCHV3KBqisOLwW77Vs+8LIJPAKuTtpzVQH2TRn1gLiYMHcV6NVH1NTcElQtAgKxj1FdQVgGodyv4RNsqWdWTj6QR5ejSmd8UhkUWbDbFLZk8W3OH4xK8mmn1cqWK5yQnpumkskQf6/OWMbOfin2WkNey7f3qVJvN6cuXIZ0oGuQxbgRbr2lKThWCaqZqXPTXsHxuzvMgAhTOYW0fXDwy9sv7CGri1K/lT1pq5l/cZmiT/H9UD6NLt9/DQQoHo/wKUA+P9QBEHHK2HBBY98MLidr6gZ7bf4ONEIta5TvF+khMkhKo80mTQrme9BU=
